# Generated by Django 5.2.3 on 2026-03-15 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_code_expires_at_user_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_code_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
