# Generated by Django 5.2.3 on 2026-03-07 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='businessmembership',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='businessmembership',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='can_delete_product',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='can_manage_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='businessmembership',
            name='can_view_sales',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='businessmembership',
            name='business',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='businesses.business'),
        ),
        migrations.AlterField(
            model_name='businessmembership',
            name='can_create_product',
            field=models.BooleanField(default=False),
        ),
    ]
