# Generated by Django 5.2.3 on 2026-03-09 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_branch_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessmembership',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.branch'),
        ),
    ]
