# Generated by Django 5.2.3 on 2026-03-09 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0006_remove_branch_is_active_business_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='manager',
        ),
        migrations.AddField(
            model_name='businessinvitation',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='businesses.branch'),
        ),
    ]
