# Generated by Django 5.2.3 on 2026-03-14 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0007_remove_branch_manager_businessinvitation_branch'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinvitation',
            name='last_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
