# Generated by Django 5.2.3 on 2025-09-30 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_user_role'),
        ('core', '0003_create_superuser'),
    ]

    operations = [
    ]
