# Generated by Django 5.2.3 on 2025-10-15 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_user_verification_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='verification_code_expires_at',
            new_name='code_expires_at',
        ),
    ]
